/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_seckill_search_service_GpuSearchService */

#ifndef _Included_com_example_seckill_search_service_GpuSearchService
#define _Included_com_example_seckill_search_service_GpuSearchService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_seckill_search_service_GpuSearchService
 * Method:    loadGpuData
 * Signature: ([J[FII)V
 */
JNIEXPORT void JNICALL Java_com_example_seckill_search_service_GpuSearchService_loadGpuData
  (JNIEnv *, jobject, jlongArray, jfloatArray, jint, jint);

/*
 * Class:     com_example_seckill_search_service_GpuSearchService
 * Method:    searchTopK
 * Signature: ([FI)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_example_seckill_search_service_GpuSearchService_searchTopK
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_example_seckill_search_service_GpuSearchService
 * Method:    freeGpuMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_seckill_search_service_GpuSearchService_freeGpuMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
