/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_seckill_search_service_LlmNativeService */

#ifndef _Included_com_example_seckill_search_service_LlmNativeService
#define _Included_com_example_seckill_search_service_LlmNativeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_seckill_search_service_LlmNativeService
 * Method:    initModel
 * Signature: (Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_seckill_search_service_LlmNativeService_initModel
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_example_seckill_search_service_LlmNativeService
 * Method:    batchInference
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_seckill_search_service_LlmNativeService_batchInference
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_example_seckill_search_service_LlmNativeService
 * Method:    freeModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_seckill_search_service_LlmNativeService_freeModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
